# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/natalie/Software/Unreal Engine/5.3.0
GAMEPROJECTFILE =/home/natalie/Repos/Unreal/NJ_GGJ24/NJ_GGJ24.uproject

TARGETS = \
	NJ_GGJ24-Linux-DebugGame  \
	NJ_GGJ24-Linux-Shipping  \
	NJ_GGJ24 \
	NJ_GGJ24Editor-Linux-DebugGame  \
	NJ_GGJ24Editor-Linux-Shipping  \
	NJ_GGJ24Editor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend NJ_GGJ24Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug NJ_GGJ24Editor-Linux-Debug


NJ_GGJ24-Linux-DebugGame:
	 $(PROJECTBUILD) NJ_GGJ24 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

NJ_GGJ24-Linux-Shipping:
	 $(PROJECTBUILD) NJ_GGJ24 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

NJ_GGJ24:
	 $(PROJECTBUILD) NJ_GGJ24 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

NJ_GGJ24Editor-Linux-DebugGame:
	 $(PROJECTBUILD) NJ_GGJ24Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

NJ_GGJ24Editor-Linux-Shipping:
	 $(PROJECTBUILD) NJ_GGJ24Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

NJ_GGJ24Editor:
	 $(PROJECTBUILD) NJ_GGJ24Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
